// Generated by scripts/gen-abi.mjs from IUnderlyingOracle, QuoteMath, BinaryPricer. Do not edit.
export const hookErrorsAbi = [
  {"type":"error","name":"ObservationUnavailable","inputs":[{"name":"t","type":"uint32"}]},
  {"type":"error","name":"Band","inputs":[]},
  {"type":"error","name":"Unreachable","inputs":[]},
  {"type":"error","name":"TooLate","inputs":[]},
  {"type":"error","name":"ZeroVariance","inputs":[]},
] as const
