// Generated by scripts/gen-abi.mjs from src/interfaces/IMarketGatekeeper.sol. Do not edit.
export const marketGatekeeperAbi = [
  {"type":"function","name":"createMarket","stateMutability":"nonpayable","inputs":[{"name":"p","type":"tuple","components":[{"name":"oracle","type":"address"},{"name":"lnStrikeWad","type":"int256"},{"name":"openTime","type":"uint64"},{"name":"expiry","type":"uint64"},{"name":"window","type":"uint32"},{"name":"cutoffBuffer","type":"uint32"},{"name":"nSamples","type":"uint32"},{"name":"budget","type":"uint256"},{"name":"quote","type":"tuple","components":[{"name":"h0Wad","type":"uint64"},{"name":"gammaSWad","type":"uint64"},{"name":"lambdaWad","type":"uint128"},{"name":"qEpochMax","type":"uint128"},{"name":"pMinWad","type":"uint64"}]},{"name":"sigmaMode","type":"uint8"},{"name":"fixedVarE36","type":"uint256"},{"name":"kernel","type":"uint8"},{"name":"yesName","type":"string"},{"name":"yesSymbol","type":"string"},{"name":"noName","type":"string"},{"name":"noSymbol","type":"string"}]}],"outputs":[{"name":"marketId","type":"uint256"}]},
  {"type":"function","name":"hook","stateMutability":"view","inputs":[],"outputs":[{"name":"","type":"address"}]},
  {"type":"function","name":"isScheduler","stateMutability":"view","inputs":[{"name":"account","type":"address"}],"outputs":[{"name":"","type":"bool"}]},
  {"type":"function","name":"schedulerCount","stateMutability":"view","inputs":[],"outputs":[{"name":"","type":"uint256"}]},
  {"type":"function","name":"schedulerOf","stateMutability":"view","inputs":[{"name":"marketId","type":"uint256"}],"outputs":[{"name":"","type":"address"}]},
  {"type":"function","name":"schedulers","stateMutability":"view","inputs":[],"outputs":[{"name":"","type":"address[]"}]},
  {"type":"error","name":"InvalidTracks","inputs":[]},
  {"type":"error","name":"NotScheduler","inputs":[]},
] as const
