import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Skeleton } from "@/components/ui/skeleton";
import { BarChart3, ArrowRightLeft, Trophy } from "lucide-react";
import { EthereumMark, LiveStatus, SparkBars, WinRing } from "./activity-visuals";
import { activityMomentum, aggregateActivity, type ActivityDisplay } from "@/lib/activity/display";
import { formatUsd } from "@/lib/format";
import "./activity.css";
const money = (n: number | null) => n === null ? 'N/A' : formatUsd(n);
const percent = (n: number | null) => n === null ? 'N/A' : `${(n * 100).toFixed(0)}%`;
const time = (n: number) => new Date(n * 1000).toISOString().slice(11, 19);
function Address({ value }: {
    value: string;
}) { const hue = [...value].reduce((n, char) => n + char.charCodeAt(0), 0) % 4; return <span className="activity-address" aria-label={value} title={value}><i className={`activity-avatar activity-avatar-${hue}`} aria-hidden="true"/>{value.slice(0, 6)}…{value.slice(-4)}</span>; }
function Empty({ status, empty }: {
    status: ActivityDisplay['status'];
    empty: string;
}) { return status === 'loading' ? <div className="activity-loading" aria-label="Loading activity" aria-busy>{[0, 1, 2].map(i => <Skeleton key={i}/>)}</div> : <p className="activity-empty">{status === 'unavailable' ? 'Activity data is not connected yet.' : status === 'error' ? 'Activity temporarily unavailable.' : empty}</p>; }
export function ActivityScreen({ display }: {
    display: ActivityDisplay;
}) {
    const data = display.snapshot ? aggregateActivity(display.snapshot) : null;
    const momentum = display.snapshot ? activityMomentum(display.snapshot) : null;
    const stats = [['Volume 1h', money(data?.volume ?? null)], ['Trades 1h', data?.trades?.toLocaleString('en-US') ?? 'N/A'], ['Win rate 1h', percent(data?.winRate ?? null)]];

    return <div className="activity-page"><div className="activity-container">
  <header className="activity-heading"><div><h1>Activity</h1><p>Live trades. Top traders. Real momentum.</p></div><div className="activity-brand-art"><span>SAME MARKETS.<br/>A MORE OPEN WORLD</span><EthereumMark/></div></header>
  <section className="activity-summary" aria-label="Activity summary, last 1 hour">
    {[{label:'Volume 1h',value:data?.volume == null ? 'N/A' : new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:1}).format(data.volume),change:momentum?.volumeChange,bars:momentum?.volumeBars,Icon:BarChart3}, {label:'Trades 1h',value:stats[1][1],change:momentum?.tradeChange,bars:momentum?.tradeBars,Icon:ArrowRightLeft}].map(({label,value,change,bars,Icon}) => <div className="activity-metric activity-momentum" key={label}><span className="activity-metric-icon"><Icon aria-hidden="true"/></span><div className="activity-metric-copy"><div className="activity-value-line">{display.status === 'loading' ? <Skeleton/> : <strong>{value}</strong>}{change != null && <span className={`activity-change ${change < 0 ? 'is-negative' : ''}`} title="Compared with the previous hour">{change < 0 ? '▼' : '▲'} {change > 0 ? '+' : ''}{change.toFixed(1)}%</span>}</div><span>{label}</span></div><SparkBars values={bars ?? null} label={label.startsWith('Volume') ? 'volume' : 'trades'}/></div>)}
    <div className="activity-metric activity-outcomes"><span className="activity-metric-icon"><Trophy aria-hidden="true"/></span><div><strong>{data?.wins ?? 'N/A'}</strong><span>Wins 1h</span></div><div><strong className="activity-down">{data?.losses ?? 'N/A'}</strong><span>Losses 1h</span></div></div>
    <div className="activity-metric activity-win"><WinRing rate={data?.winRate ?? null}/><span>Win rate<br/>1h</span></div>
  </section>
  <div className="activity-grid"><section className="activity-panel activity-feed-panel" aria-labelledby="activity-feed-title"><header><div><h2 id="activity-feed-title"><i className="activity-feed-dot" aria-hidden="true"/>Live Feed</h2><p>Real-time trades across all Phinary markets</p></div>{display.snapshot && <LiveStatus ready={display.status === 'ready'} asOf={display.snapshot.asOf} nextUpdateAt={display.nextUpdateAt}/>}</header>
  {data && data.feed.length > 0 ? <><div className="activity-desktop"><Table aria-label="Recent trades"><TableHeader><TableRow>{['Time (UTC)', 'Trader', 'Trade', 'Market', 'Amount', 'Total (USDC)'].map(s => <TableHead scope="col" key={s}>{s}</TableHead>)}</TableRow></TableHeader><TableBody>{data.feed.map(row => <TableRow key={row.id}><TableCell>{time(row.timestamp)}</TableCell><TableCell><Address value={row.account}/></TableCell><TableCell className="activity-trade"><span>{row.action}</span> <span className={`activity-${row.side}`}>{row.side === 'up' ? '▲ UP' : '▼ DOWN'}{row.amount != null && row.amount > 0 && row.total != null ? ` ${Math.round(row.total / row.amount * 100)}¢` : ''}</span></TableCell><TableCell className="activity-market">{row.market}</TableCell><TableCell>{row.amount?.toLocaleString('en-US', { maximumFractionDigits: 6 }) ?? 'N/A'}</TableCell><TableCell>{money(row.total)}</TableCell></TableRow>)}</TableBody></Table></div><div className="activity-mobile">{data.feed.map(row => <article key={row.id}><div><Address value={row.account}/><time>{time(row.timestamp)} UTC</time></div><p>{row.market}</p><div><span>{row.action} <b className={`activity-${row.side}`}>{row.side === 'up' ? '▲ UP' : '▼ DOWN'}</b></span><span>{row.amount?.toLocaleString('en-US', { maximumFractionDigits: 6 }) ?? 'N/A'} tokens</span></div><div><span>Total (USDC)</span><strong>{money(row.total)}</strong></div></article>)}</div></> : <Empty status={display.status} empty="No trades in the last hour."/>}
  </section><section className="activity-panel activity-traders-panel" aria-labelledby="activity-traders-title"><header><div><h2 id="activity-traders-title"><Trophy aria-hidden="true"/>Top Traders</h2><p>Leading traders by profit (1h)</p></div></header>{data && data.ranking.length > 0 ? <><div className="activity-desktop"><Table aria-label="Top traders by realised profit"><TableHeader><TableRow>{['#', 'Trader', 'Profit', 'Volume', 'Win rate'].map(s => <TableHead scope="col" key={s}>{s}</TableHead>)}</TableRow></TableHeader><TableBody>{data.ranking.map((row, i) => <TableRow key={row.account}><TableCell><span className={`activity-rank activity-rank-${i + 1}`}>{i + 1}</span></TableCell><TableCell><Address value={row.account}/></TableCell><TableCell className={row.profit > 0 ? 'activity-positive' : row.profit < 0 ? 'activity-down' : ''}>{row.profit > 0 ? '+' : ''}{money(row.profit)}</TableCell><TableCell>{money(row.volume)}</TableCell><TableCell>{percent(row.winRate)}</TableCell></TableRow>)}</TableBody></Table></div><div className="activity-mobile">{data.ranking.map((row, i) => <article key={row.account}><div><span>#{i + 1}</span><Address value={row.account}/></div><dl><div><dt>Profit</dt><dd className={row.profit > 0 ? 'activity-positive' : row.profit < 0 ? 'activity-down' : ''}>{row.profit > 0 ? '+' : ''}{money(row.profit)}</dd></div><div><dt>Volume</dt><dd>{money(row.volume)}</dd></div><div><dt>Win rate</dt><dd>{percent(row.winRate)}</dd></div></dl></article>)}</div></> : <Empty status={display.status} empty={display.snapshot && !display.snapshot.accountingComplete ? 'Accounting data unavailable.' : 'No ranked traders yet.'}/>}{data && data.wins === 0 && data.losses === 0 && <p className="activity-note">No resolved positions in the last hour.</p>}</section></div>
 <footer className="activity-footer"><div><strong>Phinary</strong><span>Trade the next outcome.</span></div><span>Live onchain. Always open.</span></footer></div></div>;
}
