import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Skeleton } from "@/components/ui/skeleton";
import { aggregateActivity, type ActivityDisplay } from "@/lib/activity/display";
import { formatUsd } from "@/lib/format";
import "./activity.css";
const money = (n: number | null) => n === null ? 'N/A' : formatUsd(n);
const percent = (n: number | null) => n === null ? 'N/A' : `${(n * 100).toFixed(0)}%`;
const time = (n: number) => new Date(n * 1000).toISOString().slice(11, 19);
function Address({ value }: {
    value: string;
}) { return <span className="activity-address" aria-label={value} title={value}>{value.slice(0, 6)}…{value.slice(-4)}</span>; }
function Empty({ status, empty }: {
    status: ActivityDisplay['status'];
    empty: string;
}) { return status === 'loading' ? <div className="activity-loading" aria-label="Loading activity" aria-busy>{[0, 1, 2].map(i => <Skeleton key={i}/>)}</div> : <p className="activity-empty">{status === 'unavailable' ? 'Activity data is not connected yet.' : status === 'error' ? 'Activity temporarily unavailable.' : empty}</p>; }
export function ActivityScreen({ display }: {
    display: ActivityDisplay;
}) {
    const data = display.snapshot ? aggregateActivity(display.snapshot) : null;
    const stats = [['Volume 1h', money(data?.volume ?? null)], ['Trades 1h', data?.trades?.toLocaleString('en-US') ?? 'N/A'], ['Win rate 1h', percent(data?.winRate ?? null)]];
    const ready = display.status === 'ready';
    return <div className="activity-page"><div className="activity-container">
  <header className="activity-heading"><div><h1>Activity</h1><p>Live trades. Top traders. Real momentum.</p></div><span>Last 1 hour</span></header>
  <section className="activity-summary" aria-label="Activity summary">{stats.slice(0, 2).map(([label, value]) => <div className="activity-metric" key={label}><span>{label}</span>{display.status === 'loading' ? <Skeleton /> : <strong>{value}</strong>}</div>)}<div className="activity-metric activity-outcomes"><div><span>Wins 1h</span>{display.status === 'loading' ? <Skeleton /> : <strong>{data?.wins ?? 'N/A'}</strong>}</div><div><span>Losses 1h</span>{display.status === 'loading' ? <Skeleton /> : <strong className="activity-down">{data?.losses ?? 'N/A'}</strong>}</div></div><div className="activity-metric"><span>{stats[2][0]}</span>{display.status === 'loading' ? <Skeleton /> : <strong>{stats[2][1]}</strong>}</div></section>
  <div className="activity-grid"><section className="activity-panel" aria-labelledby="activity-feed-title"><header><div><h2 id="activity-feed-title">Live Feed</h2><p>Real-time trades across all Phinary markets</p></div>{display.snapshot && <div className="activity-status"><span className={ready ? 'activity-live' : ''}>{ready ? 'Live' : 'Updates paused'}</span><small>As of {time(display.snapshot.asOf)} UTC</small></div>}</header>
  {data && data.feed.length > 0 ? <><div className="activity-desktop"><Table><TableHeader><TableRow>{['Time (UTC)', 'Trader', 'Trade', 'Market', 'Amount', 'Total (USDC)'].map(s => <TableHead key={s}>{s}</TableHead>)}</TableRow></TableHeader><TableBody>{data.feed.map(row => <TableRow key={row.id}><TableCell>{time(row.timestamp)}</TableCell><TableCell><Address value={row.account}/></TableCell><TableCell><span>{row.action}</span> <span className={`activity-${row.side}`}>{row.side === 'up' ? '▲ UP' : '▼ DOWN'}</span></TableCell><TableCell>{row.market}</TableCell><TableCell>{row.amount?.toLocaleString('en-US', { maximumFractionDigits: 6 }) ?? 'N/A'}</TableCell><TableCell>{money(row.total)}</TableCell></TableRow>)}</TableBody></Table></div><div className="activity-mobile">{data.feed.map(row => <article key={row.id}><div><Address value={row.account}/><time>{time(row.timestamp)} UTC</time></div><p>{row.market}</p><div><span>{row.action} <b className={`activity-${row.side}`}>{row.side === 'up' ? '▲ UP' : '▼ DOWN'}</b></span><span>{row.amount?.toLocaleString('en-US', { maximumFractionDigits: 6 }) ?? 'N/A'} tokens</span></div><div><span>Total (USDC)</span><strong>{money(row.total)}</strong></div></article>)}</div></> : <Empty status={display.status} empty="No trades in the last hour."/>}
  </section><section className="activity-panel" aria-labelledby="activity-traders-title"><header><div><h2 id="activity-traders-title">Top Traders</h2><p>Leading traders by profit (1h)</p></div></header>{data && data.ranking.length > 0 ? <><div className="activity-desktop"><Table><TableHeader><TableRow>{['#', 'Trader', 'Profit', 'Volume', 'Win rate'].map(s => <TableHead key={s}>{s}</TableHead>)}</TableRow></TableHeader><TableBody>{data.ranking.map((row, i) => <TableRow key={row.account}><TableCell>{i + 1}</TableCell><TableCell><Address value={row.account}/></TableCell><TableCell className={row.profit > 0 ? 'activity-positive' : row.profit < 0 ? 'activity-down' : ''}>{row.profit > 0 ? '+' : ''}{money(row.profit)}</TableCell><TableCell>{money(row.volume)}</TableCell><TableCell>{percent(row.winRate)}</TableCell></TableRow>)}</TableBody></Table></div><div className="activity-mobile">{data.ranking.map((row, i) => <article key={row.account}><div><span>#{i + 1}</span><Address value={row.account}/></div><dl><div><dt>Profit</dt><dd className={row.profit > 0 ? 'activity-positive' : row.profit < 0 ? 'activity-down' : ''}>{row.profit > 0 ? '+' : ''}{money(row.profit)}</dd></div><div><dt>Volume</dt><dd>{money(row.volume)}</dd></div><div><dt>Win rate</dt><dd>{percent(row.winRate)}</dd></div></dl></article>)}</div></> : <Empty status={display.status} empty={display.snapshot && !display.snapshot.accountingComplete ? 'Accounting data unavailable.' : 'No ranked traders yet.'}/>}{data && data.wins === 0 && data.losses === 0 && <p className="activity-note">No resolved positions in the last hour.</p>}</section></div>
 </div></div>;
}
