[profile.default]
src = "src"
test = "test"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000000
via_ir = true
gas_limit = "18446744073709551615"
memory_limit = 4294967296
fs_permissions = [{ access = "read", path = "./data" }]
remappings = [
  "forge-std/=lib/forge-std/src/",
  "solmate/=lib/solmate/",
  "v4-core/=lib/v4-core/",
  "@uniswap/v4-core/=lib/v4-core/",
]
[fuzz]
runs = 256
[rpc_endpoints]
mainnet = "https://ethereum-rpc.publicnode.com"

[lint]
lint_on_build = false
