import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { isAddress } from 'viem'
import { describe, expect, it, vi } from 'vitest'

import { loadIndexerDeployment } from '../src/deployment.ts'

const repoRoot = path.resolve(import.meta.dirname, '..', '..')
const sepoliaDeploymentPath = path.join(repoRoot, 'deployments', 'unichain-sepolia.json')
const localDeploymentPath = path.join(repoRoot, 'deployments', 'local.json')

type DeploymentJson = {
  chainId: number
  rpcUrl: string
  predictionHook: string
  underlyingOracle: string
  poolManager: string
  deployBlock: number
  multicall3?: string
  marketGatekeeper?: string
  marketSchedulers?: string[]
  legacyMarketSchedulers?: string[]
  legacyPredictionHooks?: string[]
  underlyings?: { symbol: string; oracle: string }[]
}

const readDeployment = (file: string) => JSON.parse(readFileSync(file, 'utf8')) as DeploymentJson

describe('loadIndexerDeployment', () => {
  it('defaults to unichain-sepolia and parses its file field by field, with safe snapshot initialization', () => {
    // Read the committed file rather than freezing values that change on every redeploy
    const file = readDeployment(sepoliaDeploymentPath)
    const deployment = loadIndexerDeployment({})

    expect(deployment.chainId).toBe(1301)
    expect(deployment).toEqual({
      chainId: file.chainId,
      rpcUrl: file.rpcUrl,
      rpcUrls: [file.rpcUrl],
      hook: file.predictionHook,
      oracle: file.underlyingOracle,
      poolManager: file.poolManager,
      multicall3: file.multicall3,
      deployBlock: file.deployBlock,
      snapshotStartBlock: file.deployBlock,
      marketGatekeeper: file.marketGatekeeper,
      marketSchedulers: file.marketSchedulers,
      legacyMarketSchedulers: file.legacyMarketSchedulers,
      legacyPredictionHooks: file.legacyPredictionHooks,
      underlyings: file.underlyings!.map(({ symbol, oracle }) => ({ symbol, oracle })),
    })
    expect(Number.isSafeInteger(deployment.deployBlock) && deployment.deployBlock > 0).toBe(true)
    for (const a of [deployment.hook, deployment.oracle, deployment.poolManager]) expect(isAddress(a)).toBe(true)
  })

  it('parses the track migration of the unichain-sepolia file: gatekeeper, schedulers, legacy lists and underlyings', () => {
    const deployment = loadIndexerDeployment({})

    expect(isAddress(deployment.marketGatekeeper!)).toBe(true)
    expect(deployment.marketSchedulers.length).toBeGreaterThan(0)
    expect(deployment.legacyMarketSchedulers.length).toBeGreaterThan(0)
    for (const a of [...deployment.marketSchedulers, ...deployment.legacyMarketSchedulers]) expect(isAddress(a)).toBe(true)
    expect(deployment.legacyPredictionHooks.length).toBeGreaterThan(0)
    for (const legacy of deployment.legacyPredictionHooks) {
      expect(isAddress(legacy)).toBe(true)
      expect(legacy.toLowerCase()).not.toBe(deployment.hook.toLowerCase())
    }
    expect(deployment.underlyings.map((u) => u.symbol)).toEqual(expect.arrayContaining(['ETH', 'SOL']))
    expect(deployment.underlyings.find((u) => u.symbol === 'ETH')!.oracle).toBe(deployment.oracle)
  })

  it('rejects invalid snapshot starts, including one before deployBlock', () => {
    const { deployBlock } = loadIndexerDeployment({})
    for (const value of [String(deployBlock - 1), '-1', 'NaN', `${deployBlock}.5`, '9007199254740992']) {
      expect(() => loadIndexerDeployment({ SNAPSHOT_START_BLOCK: value })).toThrow('SNAPSHOT_START_BLOCK')
    }
  })

  it('honors SNAPSHOT_START_BLOCK when set', () => {
    const { deployBlock } = loadIndexerDeployment({})
    const deployment = loadIndexerDeployment({ SNAPSHOT_START_BLOCK: String(deployBlock + 100) })

    expect(deployment.snapshotStartBlock).toBe(deployBlock + 100)
  })

  it.skipIf(!existsSync(localDeploymentPath))('reads deployments/local.json for PONDER_NETWORK=local', () => {
    // local.json is regenerated by every local run (e.g. a fresh anvil fork on a different port), so
    // this asserts against whatever the file currently says rather than a value frozen at write time.
    const file = JSON.parse(readFileSync(localDeploymentPath, 'utf8')) as DeploymentJson
    const deployment = loadIndexerDeployment({ PONDER_NETWORK: 'local' })

    expect(deployment.rpcUrl).toBe(file.rpcUrl)
    expect(deployment.deployBlock).toBe(file.deployBlock)
    expect(deployment.snapshotStartBlock).toBe(file.deployBlock)
    expect(deployment.marketSchedulers).toEqual(file.marketSchedulers ?? [])
    expect(deployment.legacyPredictionHooks).toEqual(file.legacyPredictionHooks ?? [])
  })

  it('defaults the track keys to empty and underlyings to the flat ETH oracle for a file without them', async () => {
    const {
      marketGatekeeper: _gatekeeper,
      marketSchedulers: _schedulers,
      legacyMarketSchedulers: _legacySchedulers,
      legacyPredictionHooks: _legacy,
      underlyings: _underlyings,
      multicall3: _multicall3,
      ...premigration
    } = readDeployment(sepoliaDeploymentPath)
    vi.resetModules()
    vi.doMock('node:fs', async (importOriginal) => ({
      ...(await importOriginal<typeof import('node:fs')>()),
      readFileSync: () => JSON.stringify(premigration),
    }))
    try {
      const { loadIndexerDeployment: loadFromPremigrationFile } = await import('../src/deployment.ts')
      const deployment = loadFromPremigrationFile({})

      expect(deployment.hook).toBe(premigration.predictionHook)
      expect(deployment.marketGatekeeper).toBeUndefined()
      expect(deployment.marketSchedulers).toEqual([])
      expect(deployment.legacyMarketSchedulers).toEqual([])
      expect(deployment.legacyPredictionHooks).toEqual([])
      expect(deployment.underlyings).toEqual([{ symbol: 'ETH', oracle: premigration.underlyingOracle }])
      expect(deployment.multicall3).toBe('0xcA11bde05977b3631167028862bE2a173976CA11')
    } finally {
      vi.doUnmock('node:fs')
      vi.resetModules()
    }
  })

  it('overrides the RPC URL with PONDER_RPC_URL_1301', () => {
    const deployment = loadIndexerDeployment({ PONDER_RPC_URL_1301: 'http://example.invalid' })

    expect(deployment.rpcUrl).toBe('http://example.invalid')
    expect(deployment.rpcUrls).toEqual(['http://example.invalid'])
  })

  it('reads several comma-separated RPC URLs from PONDER_RPC_URL_1301', () => {
    const deployment = loadIndexerDeployment({ PONDER_RPC_URL_1301: ' https://a.invalid , https://b.invalid,' })

    expect(deployment.rpcUrls).toEqual(['https://a.invalid', 'https://b.invalid'])
    expect(() => loadIndexerDeployment({ PONDER_RPC_URL_1301: 'https://a.invalid,wss://b.invalid' })).toThrow(/http\(s\) URLs/)
  })
})
