import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

import { loadIndexerDeployment } from '../src/deployment.ts'

const repoRoot = path.resolve(import.meta.dirname, '..', '..')
const localDeploymentPath = path.join(repoRoot, 'deployments', 'local.json')

describe('loadIndexerDeployment', () => {
  it('keeps event indexing at deployBlock but starts snapshots after initialization', () => {
    const deployment = loadIndexerDeployment({})

    expect(deployment.chainId).toBe(1301)
    expect(deployment.deployBlock).toBe(63569270)
    expect(deployment.snapshotStartBlock).toBe(63569470)
  })

  it.each(['63569270', '-1', 'NaN', '63569470.5', '9007199254740992'])('rejects invalid snapshot start %s', value => {
    expect(() => loadIndexerDeployment({ SNAPSHOT_START_BLOCK: value })).toThrow('SNAPSHOT_START_BLOCK')
  })

  it('honors SNAPSHOT_START_BLOCK when set', () => {
    const deployment = loadIndexerDeployment({ SNAPSHOT_START_BLOCK: '63600000' })

    expect(deployment.snapshotStartBlock).toBe(63600000)
  })

  it.skipIf(!existsSync(localDeploymentPath))('reads deployments/local.json for PONDER_NETWORK=local', () => {
    // local.json is regenerated by every local run (e.g. a fresh anvil fork on a different port), so
    // this asserts against whatever the file currently says rather than a value frozen at write time.
    const file = JSON.parse(readFileSync(localDeploymentPath, 'utf8')) as {
      rpcUrl: string
      deployBlock: number
      marketScheduler?: string
      legacyPredictionHooks?: string[]
    }
    const deployment = loadIndexerDeployment({ PONDER_NETWORK: 'local' })

    expect(deployment.rpcUrl).toBe(file.rpcUrl)
    expect(deployment.deployBlock).toBe(file.deployBlock)
    expect(deployment.snapshotStartBlock).toBe(file.deployBlock)
    expect(deployment.marketScheduler).toBe(file.marketScheduler)
    expect(deployment.legacyPredictionHooks).toEqual(file.legacyPredictionHooks ?? [])
  })

  it('preserves the configured scheduler and legacy Hook registry', () => {
    const deployment = loadIndexerDeployment({})

    expect(deployment.marketScheduler).toBe('0x511fFFb9fE5d393B10bF185A9c580A732Eff44Dd')
    expect(deployment.legacyPredictionHooks).toEqual(['0x62bBCbA51cbFC8D0C932e482bD8F62590fEeeAa8'])
  })

  it('overrides the RPC URL with PONDER_RPC_URL_1301', () => {
    const deployment = loadIndexerDeployment({ PONDER_RPC_URL_1301: 'http://example.invalid' })

    expect(deployment.rpcUrl).toBe('http://example.invalid')
  })
})
