// Regenerates src/abi/*.generated.ts and test/fixtures/MockERC20.json from the Foundry build in ../../out.
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const pkg = join(here, '..')
const out = process.env.FOUNDRY_OUT ?? join(pkg, '..', '..', 'out')

function artifact(file, name) {
  const p = join(out, file, `${name}.json`)
  return existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : undefined
}

function strip(item) {
  const clean = (params) =>
    params?.map(({ internalType, components, ...rest }) =>
      components ? { ...rest, components: clean(components) } : rest,
    )
  const { inputs, outputs, ...rest } = item
  return { ...rest, ...(inputs ? { inputs: clean(inputs) } : {}), ...(outputs ? { outputs: clean(outputs) } : {}) }
}

function signature(item) {
  const t = (p) => (p.components ? `(${p.components.map(t).join(',')})${p.type.slice(5)}` : p.type)
  return `${item.name}(${(item.inputs ?? []).map(t).join(',')})`
}

function emit(file, exportName, abi, source) {
  const entries = abi.map((e) => `  ${JSON.stringify(e)},`).join('\n')
  const body = `// Generated by scripts/gen-abi.mjs from ${source}. Do not edit.\nexport const ${exportName} = [\n${entries}\n] as const\n`
  writeFileSync(join(pkg, 'src', 'abi', file), body)
  console.log(`wrote src/abi/${file} (${abi.length} entries)`)
}

const iface = artifact('IPredictionHook.sol', 'IPredictionHook')
if (!iface) throw new Error(`missing ${out}/IPredictionHook.sol/IPredictionHook.json; run forge build first`)
emit('predictionHook.generated.ts', 'predictionHookAbi', iface.abi.map(strip), 'src/interfaces/IPredictionHook.sol')

const scheduler = artifact('IMarketScheduler.sol', 'IMarketScheduler')
if (!scheduler) throw new Error(`missing ${out}/IMarketScheduler.sol/IMarketScheduler.json; run forge build first`)
emit(
  'marketScheduler.generated.ts',
  'marketSchedulerAbi',
  scheduler.abi.map(strip),
  'src/interfaces/IMarketScheduler.sol',
)

const token = artifact('OutcomeToken.sol', 'OutcomeToken')
if (!token) throw new Error('missing OutcomeToken artifact')
emit(
  'outcomeToken.generated.ts',
  'outcomeTokenAbi',
  token.abi.filter((x) => x.type !== 'constructor').map(strip),
  'src/OutcomeToken.sol',
)

const errorSources = [
  ['PredictionHook.sol', 'PredictionHook'],
  ['UnderlyingOracleHook.sol', 'UnderlyingOracleHook'],
  ['IUnderlyingOracle.sol', 'IUnderlyingOracle'],
  ['QuoteMath.sol', 'QuoteMath'],
  ['BinaryPricer.sol', 'BinaryPricer'],
]
const seen = new Map()
const used = []
for (const [file, name] of errorSources) {
  const a = artifact(file, name)
  if (!a) continue
  used.push(name)
  for (const e of a.abi.filter((x) => x.type === 'error')) {
    const s = strip(e)
    if (!seen.has(signature(s))) seen.set(signature(s), s)
  }
}
emit('hookErrors.generated.ts', 'hookErrorsAbi', [...seen.values()], used.join(', '))

const mock = artifact('MockERC20.sol', 'MockERC20')
if (mock) {
  writeFileSync(
    join(pkg, 'test', 'fixtures', 'MockERC20.json'),
    JSON.stringify({ abi: mock.abi.map(strip), bytecode: mock.bytecode.object }) + '\n',
  )
  console.log('wrote test/fixtures/MockERC20.json')
}
