[profile.default]
src = "src"
test = "test"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
fuzz = { runs = 256 }
remappings = [
  "forge-std/=lib/forge-std/src/",
  "solmate/=lib/solmate/",
  "v4-core/=lib/v4-core/",
  "@uniswap/v4-core/=lib/v4-core/",
]
